invitation/config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  get '/showall', to: 'reservations#showall'

  root to:'static_pages#home'

end

invitation/app/models/reservation.rb
class Reservation < ActiveRecord::Base

  before_create :assign_unique_token



  def to_param
    permalink
  end

  private

  def assign_unique_token
    self.permalink = SecureRandom.urlsafe_base64(nil,true) ;
  end

  def unique_token?
    self.class.count(:conditions => {:id => id}) == 0
  end

end

invitation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

invitation/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
=begin
  def index
    @reservations = Reservation.all
  end
=end

  # GET /reservations/1
  # GET /reservations/1.json

  def showall
    @reservations = Reservation.all
  end


  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
=begin
  def edit
  end
=end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.nb_personne.blank? || !@reservation.nb_personne.between?(0,100)
      @reservation.nb_personne = 0;
    end
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: "Merci!" }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
=begin
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find_by_permalink(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:name, :nb_personne, :email)
    end
end

invitation/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @reservation = Reservation.new
  end

end

invitation/app/helpers/application_helper.rb
module ApplicationHelper
end

invitation/app/helpers/reservations_helper.rb
module ReservationsHelper
end

invitation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emma Johns</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'js/jquery' %>
  <%= javascript_include_tag 'js/plugins' %>
  <%= javascript_include_tag 'js/jquery.gmap' %>


  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="author" content="SemiColonWeb"/>

  <!-- Stylesheets
  <!--============================================= &ndash;&gt;
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="css/bootstrap.css" type="text/css" />
  <link rel="stylesheet" href="style.css" type="text/css" />
  <link rel="stylesheet" href="css/dark.css.scss" type="text/css" />
  <link rel="stylesheet" href="css/font-icons.css" type="text/css" />
  <link rel="stylesheet" href="css/animate.css" type="text/css" />
  <link rel="stylesheet" href="css/magnific-popup.css" type="text/css" />

  <link rel="stylesheet" href="css/responsive.css" type="text/css" />
  <link rel="stylesheet" href="css/colors.css" type="text/css" />
  <link rel="stylesheet" href="css/fonts.css" type="text/css" />-->
  <%= stylesheet_link_tag 'css/responsive', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'css/colors.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'css/fonts.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'css/font-icons.css', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="shortcut icon"  href="<%= asset_path 'invitation/tabicon.jpg' %>" type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
  <!--[if lt IE 9]>
  <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
  <![endif]-->

  <!-- External JavaScripts
  ============================================= -->

  <!-- Document Title
  ============================================= -->
  <title>Emma Johns</title>
</head>
<%= yield %>
<%= javascript_include_tag 'js/functions.js' %>
</html>

invitation/app/views/reservations/_form.html.erb
<%= form_for @reservation, html: {class: "bottommargin-lg divcenter", style: "max-width: 500px;"} do |f| %>
    <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

          <ul>
            <% @reservation.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="col_full">
      <%= f.text_field :name, id: "invitation-rsvp-name", class: "form-control input-lg", placeholder: "Votre nom complet" %>
    </div>
    <div class="col_full">
      <%= f.number_field :nb_personne, min: "0", max: "100", id: "invitation-rsvp-guests", required: "",
                         class: "form-control input-lg", placeholder: "Nombre de personnes avec vous" %>
    </div>
    <div class="col_full">
      <%= f.text_field :email, id: "invitation-rsvp-email", required: "",
                       class: "form-control input-lg", placeholder: "Votre email" %>
    </div>

    <div class="col_full nobottommargin">
      <%= f.submit name: "invitation-rsvp-submit", id: "invitation-rsvp-submit", class: "button button-3d btn-block nomargin button-dark button-xlarge", value: "Soumettre" %>
    </div>
<% end %>

invitation/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

invitation/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nb personne</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.nb_personne %></td>
        <td><%= reservation.place %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

invitation/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

invitation/app/views/reservations/show.html.erb
<style>

    ul.confirm-info li p {
        margin-bottom: 5px;
    }

    a:hover {
        background-color: transparent;
        text-decoration: none;
    }

    .button-retour {
        color: rgb(229, 222, 215);
        position: relative;
        top: 31%;
        left: 15px;
        text-shadow: none;
    }

    .button-retour:hover {
        color: #845b6d;
        cursor: pointer;
    }

    .button-container {
        margin-top: -15px;
        margin-left: -15px;
        position: absolute;
        padding-right: 30px;
        height: 100%;
        border-right: 2px solid black;
        background: rgba(0, 0, 0, 0.30) !important;
    }

    .msgtitle.panel-heading {
        position: relative;
    }

    .successmsg p {
        font-family: 'css/fonts/Oranienbaum.ttf', sans-serif;
    }

    div.msgtitle.panel-heading {
        height: 50px;
    }

    div#notice-reservation {
        font-size: 5em;
        color: #000000;
        text-shadow: none;
        margin-bottom: 10px;

    }

    @media (max-device-width: 480px) {

        .confirm-info li p {
            font-size: 14px;
            /* equivalent to 16px */
            line-height: 1.375;
            /* equivalent to 22px */
        }

        ul.confirm-info {
            padding: 0;
            margin: 0;
        }

        ul.confirm-info li {
            padding: 0;
            padding-bottom: 50px;
        }

    }

</style>


<div id="confirm-bg">
  <img src="<%= asset_path('invitation/intro.jpg') %>" alt=""/>
</div>

<div class="container center clearfix vertical-middle ">
  <div class="container">
    <div class="row col-md-12">
      <div id="notice-reservation"><%= notice %></div>
      <div class="style-msg2 successmsg transparent">
        <div class="msgtitle panel-heading">
          <div class="button-container">

            <a href="<%= root_path %>">
              <span class="button-retour">
               <i class="icon-chevron-left"></i>
              Retour
            </span>
            </a>
          </div>

        </div>
        <div class="sb-msg panel-body">
          <ul class="confirm-info">
            <li>
              <p><strong>NOM:</strong></p>

              <p><%= @reservation.name %></p>

            </li>
            <li>
              <p><strong>INVITÉS:</strong></p>

              <p><%= @reservation.nb_personne %></p>
            </li>
            <li>
              <p><strong>EMAIL:</strong></p>

              <p><%= @reservation.email %></p>
            </li>

          </ul>
        </div>
      </div>
    </div>

  </div>


</div>
</div>


<!--

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>
-->

invitation/app/views/reservations/showall.html.erb
<div class="container">

  <div class="row col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Nom</th>
        <th>Email</th>
      </tr>

      </thead>
      <tbody>
      <% @reservations.each do |r| %>
          <tr>
            <td><%= r.name %></td>
            <td><%= r.email%></td>
          </tr>

      <% end %>
      </tbody>
    </table>

  </div>
</div>

invitation/app/views/static_pages/home.html.erb
<body class="stretched">

<!-- Document Wrapper
============================================= -->
<div id="wrapper" class="clearfix">

  <div id="most-toppest"></div>

  <section id="slider" class="slider-parallax full-screen page-section dark clearfix">

    <div class="fslider" data-speed="2000" data-pause="6000" data-animation="fade" data-arrows="false" data-pagi="false" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; background-color: #2d2a2a;">
      <div class="flexslider">
        <div class="slider-wrap">
          <div class="slide full-screen force-full-screen" style="center: center; background-size: cover; height: 100% !important;"></div>
        </div>
      </div>
    </div>

    <div class="container vertical-middle dark center clearfix" style="z-index: 2;">

      <div id="invitation-head-title" class="invitation-head clearfix">
        <div class="first-name">Emma</div>
        <div class="last-name">Johns</div>
      </div>

      <div style="">
        <div class="divider divider-short divider-center ">&nbsp</div>

      </div>


      <h2 class="invitation-subhead"><span>LOCOMOTION </span></h2>

      <p class="invitation-subhead">Le premier album d'Emma Johns sortira le 3 mai prochain</p>

      <div id="countdown-ex1" class="countdown countdown-large coming-soon divcenter" style="max-width:700px;"></div>
      <a href="#section-rsvp" ><div class="invitation-phrase"><h4>Réservez votre place ci-dessous</h4></div></a>


    </div>

    <a href="#" data-scrollto="#section-events" class="one-page-arrow">
      <i id="fleche" class="icon-angle-down infinite animated fadeInDown " style="font-size: 50px;"></i></a>

    <script>
        jQuery(document).ready(function ($) {
            var newDate = new Date(2015, 4, 3, 14, 0, 0, 0);
            $('#countdown-ex1').countdown({until: newDate});
        });
        jQuery(window).load(function () {
            var t = setTimeout(function () {
                $('.flexslider .slide').resize();
            }, 500);
        });
    </script>

  </section>

  <!-- Header
  ============================================= -->
  <header id="header">

    <div id="header-wrap">

      <div class="container clearfix">

        <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

        <div id="logo"></div>

        <!-- Primary Navigation
        ============================================= -->
        <nav id="primary-menu" class="style-2 center">

          <ul class="one-page-menu">
            <li><a href="#" data-href="#most-toppest">
              <div>Bienvenue</div>
            </a></li>
            <li><a href="#" data-href="#section-events">
              <div>Lancement</div>
            </a></li>
            <li><a href="#" data-href="#section-locomotion">
              <div>Locomotion</div>
            </a></li>
            <li><a href="#" data-href="#section-bio">
              <div>Biographie</div>
            </a></li>
            <li><a href="#" data-href="#section-rsvp">
              <div>RSVP</div>
            </a></li>
            <li><a href="#" data-href="#section-locations">
              <div>La salle</div>
            </a></li>
          </ul>

        </nav>
        <!-- #primary-menu end -->

      </div>

    </div>

  </header>
  <!-- #header end -->

  <!-- Content
  ============================================= -->
  <section id="content">

    <div class="content-wrap">

      <div class="container clearfix">


        <div id="section-events" class="heading-block title-center topmargin-lg page-section">
          <h2>Lancement d'album</h2>
          <span></span>
        </div>

        <div class="col_one_third">
          <div class="feature-box center media-box fbox-bg">
            <div class="fbox-media">
              <img src="<%= asset_path 'invitation/IMG_3169.jpg' %>" alt="Image">
            </div>
          </div>
        </div>
        <div class="col_three_fifth" style="text-align: justify;">
          La pianiste et compositrice Montréalaise Emma Johns sort son tout premier album <i>Locomotion!</i> <br/><br/>

          Afin de célébrer l'accomplissement de ce premier album, Emma vous invite à un lancement officiel qui aura lieu
          le dimanche 3 mai, à 14h00, à la salle Claude-Léveillée de la Place des Arts. (métro place-des-arts). Elle
          offrira un concert inédit présentant ses compositions pour piano solo qui seront disponibles sur Locomotion.
          <br/><br/>
          Il y aura également une petite réception à la fin du concert durant laquelle vous aurez la chance de parler
          avec Emma et de vous procurer son album.
          <br/><br/>
          Le concert est gratuit et les places sont limitées. Il vous suffit simplement de réserver votre place en
          inscrivant votre nom au bas de cette page, à l'endroit prévu à cet effet.
        </div>


        <div class="clear"></div>

        <div id="section-locomotion" class="heading-block center topmargin page-section">
          <h2>Locomotion</h2>
          <span>Un aperçu du projet</span>
        </div>


        <div id="" class="section nomargin clearfix" style="position: relative;">

          <iframe src="//player.vimeo.com/video/114263474" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

          <p><br/><br/><br/></p>
          <iframe src="//player.vimeo.com/video/118062346" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <p><br/><br/><br/></p>

        </div>


        <div class="clear"></div>

        <div id="section-bio" class="heading-block title-center page-section">
          <h2>Biographie</h2>
          <span></span>
        </div>

        <div class="col-md-12 bottommargin">
          <div class="team team-list clearfix">
            <div class="team-image" style="width: 150px;">
              <img class="img-circle" src="<%= asset_path 'invitation/1.jpg' %>" alt="Emma Johns">
            </div>
            <div class="team-desc">
              <div class="team-title"><h4>Emma Johns</h4><span>pianiste</span></div>
              <div class="team-content">
                <i>À venir</i>
              </div>
              <div class="line topmargin-sm nobottommargin"></div>
              <a href="https://www.facebook.com/emmajohnspiano" target="_blank" class="social-icon si-borderless si-small si-facebook" title="Facebook">
                <i class="icon-facebook"></i>
                <i class="icon-facebook"></i>
              </a>

            </div>
          </div>
        </div>


        <div class="clear"></div>

        <div class="section notopmargin footer-stick">
          <div class="">

            <div id="section-rsvp" class="heading-block title-center topmargin page-section">
              <h2>RSVP</h2>
              <span>Vous êtes invités à inscrire votre nom ci-bas afin de confirmer votre présence au lancement</span>
            </div>

            <%= render 'reservations/form' %>

          </div>
        </div>


        <div id="section-locations" class="heading-block title-center topmargin-lg page-section">
          <h2>Salle Claude-Léveillée</h2>
                    <span>Voici l'emplacement de la salle de spectacle Claude-Léveillée de la
                      Place des Arts <br/>
                    260, Boulevard de Maisonneuve Ouest
                    </span>
        </div>

      </div>


      <div class="notopmargin center" style=" padding-bottom: 20px;">
        <div class="map">

        </div>

      </div>


    </div>

  </section>
  <!-- #content end -->

  <!-- Footer
  ============================================= -->
  <footer id="footer" class="dark">

    <!-- Copyrights
    ============================================= -->

  </footer>
  <!-- #footer end -->

</div>
<!-- #wrapper end -->

<!-- Go To Top
============================================= -->
<div id="gotoTop" class="icon-angle-up"></div>

<!-- Footer Scripts
============================================= -->
</body>

<script>
    //http://jsfiddle.net/ZnGpb/1/
    function get_static_style(styles) {
        var result = [];
        styles.forEach(function (v, i, a) {

            var style = '';
            if (v.stylers) { // only if there is a styler object
                if (v.stylers.length > 0) { // Needs to have a style rule to be valid.
                    style += (v.hasOwnProperty('featureType') ? 'feature:' + v.featureType : 'feature:all') + '|';
                    style += (v.hasOwnProperty('elementType') ? 'element:' + v.elementType : 'element:all') + '|';
                    v.stylers.forEach(function (val, i, a) {
                        var propertyname = Object.keys(val)[0];
                        var propertyval = val[propertyname].toString().replace('#', '0x');
                        style += propertyname + ':' + propertyval + '|';
                    });
                }
            }
            result.push('style=' + encodeURIComponent(style));
        });

        return result.join('&');
    }


    var mapStyle = [{
        "featureType": "road",
        "elementType": "geometry",
        "stylers": [{"lightness": 100}, {"visibility": "simplified"}]
    }, {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [{"visibility": "on"}, {"color": "#C6E2FF"}]
    }, {
        "featureType": "poi",
        "elementType": "geometry.fill",
        "stylers": [{"color": "#C5E3BF"}]
    }, {"featureType": "road", "elementType": "geometry.fill", "stylers": [{"color": "#D1D1B8"}]}];

    var src = get_static_style(mapStyle);
    $(".map").append("<img src=\"http://maps.googleapis.com/maps/api/staticmap?center=260,+Boulevard+de+Maisonneuve+Ouest&zoom=17&size=1000x600&feature=all&maptype=roadmap&sensor=false&format=jpeg&visual_refresh=true&markers=size:mid%7Ccolor:red%7C260,+Boulevard+de+Maisonneuve+Ouest&" + src + "\">");


</script>